In [1]:
import pandas as pd
import re

In [ ]:
df = pd.read_csv(r"..\_raw_data\discord_messages_processed.csv")
df['Date'] = pd.to_datetime(df['Date'])
df.head()

  Author                             Date                Content
0      A 2023-01-01 00:00:31.203000+07:00      happy polla brody
1      B 2023-01-01 00:00:47.536000+07:00                  <URL>
2      A 2023-01-01 00:14:22.630000+07:00               <ATTACH>
3      A 2023-01-01 00:14:26.018000+07:00  isis beheading videos
4      B 2023-01-01 00:15:00.567000+07:00        yo shoutout!! !

In [40]:
# Generate (Message, Response) pairs
mr = pd.DataFrame(columns=['m', 'r'])
i = 0

while i < len(df) - 1:
	if df['Author'][i] == "A" or df['Author'][i + 1] == "B":
		i = i + 1
		continue
	
	m = df['Content'][i]
	r = df['Content'][i + 1]

	if '<URL>' in m or '<ATTACH>' in m or '<URL>' in r or '<ATTACH>' in r:
		i = i + 2
		continue

	if len(m) < 10 or len(r) < 10:
		i = i + 2
		continue

	if (df['Date'][i + 1] - df['Date'][i]).total_seconds() > 60:
		i = i + 2
		continue

	mr = pd.concat([mr, pd.DataFrame({'m': [m], 'r': [r]})], ignore_index=True)

	i	= i + 2

len(mr)

2578

In [44]:
mr_sample = mr.sample(n=50, random_state=20)
mr_sample.to_csv(r'..\_training_data\mr_pairs.csv', index=False)
mr_sample.head(10)

,m,r
900,expensive..,common ccp w
265,but but.. .none of thse characters are playabl...,w w w wwhat the h aell!!!!
905,but twhy you hit the drum then stop,which part?
1305,cock shrink,would intellifuck counteract the effect??
2170,gonna do this in real life,permanent inventory upgrade
155,bitch ass roommate is nagging,alright brody
250,me when it has been 3 years since call of duty...,what you mean been at least 30 years
1792,multiple attack types,this the gun combat???
1506,marriage over,dit me may ... naruto kun. . . .. . . . .> >!>...
849,art made from instructions of how multiple poi...,ok bro you going too far